# Generated by Django 5.1.6 on 2025-10-19 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_analysis', '0011_remove_report_source_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for this API key', max_length=100)),
                ('key', models.CharField(help_text='The actual API key', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit_per_hour', models.IntegerField(default=100, help_text='Maximum requests per hour')),
                ('last_used', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='reportdynamicanalysis',
            old_name='files',
            new_name='report',
        ),
        migrations.RemoveField(
            model_name='reportdynamicanalysis',
            name='commands',
        ),
        migrations.RemoveField(
            model_name='reportdynamicanalysis',
            name='dns',
        ),
        migrations.RemoveField(
            model_name='reportdynamicanalysis',
            name='ips',
        ),
        migrations.RemoveField(
            model_name='reportdynamicanalysis',
            name='num_commands',
        ),
        migrations.RemoveField(
            model_name='reportdynamicanalysis',
            name='num_files',
        ),
        migrations.RemoveField(
            model_name='reportdynamicanalysis',
            name='num_network_connections',
        ),
        migrations.RemoveField(
            model_name='reportdynamicanalysis',
            name='num_system_calls',
        ),
        migrations.RemoveField(
            model_name='reportdynamicanalysis',
            name='syscalls',
        ),
        migrations.CreateModel(
            name='AnalysisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purl', models.CharField(help_text='Package URL submitted for analysis', max_length=500)),
                ('package_name', models.CharField(blank=True, max_length=200)),
                ('package_version', models.CharField(blank=True, max_length=100)),
                ('ecosystem', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='package_analysis.reportdynamicanalysis')),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_tasks', to='package_analysis.apikey')),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
