# Generated by Django 5.1.6 on 2025-10-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_analysis', '0012_apikey_rename_files_reportdynamicanalysis_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='download_url',
            field=models.URLField(blank=True, help_text='URL to download the analysis report JSON file'),
        ),
    ]
