# Generated by Django 5.1.6 on 2025-10-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_analysis', '0013_analysistask_download_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysistask',
            name='download_url',
            field=models.URLField(blank=True, help_text='URL to download the analysis report JSON file', null=True),
        ),
    ]
