# Generated by Django 5.1.6 on 2025-10-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_analysis', '0014_alter_analysistask_download_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='analysistask',
            index=models.Index(fields=['purl'], name='package_ana_purl_c7b6b7_idx'),
        ),
        migrations.AddIndex(
            model_name='analysistask',
            index=models.Index(fields=['status', 'created_at'], name='package_ana_status_adc3e7_idx'),
        ),
        migrations.AddIndex(
            model_name='analysistask',
            index=models.Index(fields=['api_key', 'created_at'], name='package_ana_api_key_3af360_idx'),
        ),
        migrations.AddConstraint(
            model_name='analysistask',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('api_key', 'idempotency_key'), name='unique_api_key_idempotency_key'),
        ),
    ]
