# Generated by Django 5.1.6 on 2025-10-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_analysis', '0015_analysistask_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='error_category',
            field=models.CharField(blank=True, help_text='Category of error (e.g., docker_error, timeout_error, analysis_error)', max_length=50),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='error_details',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed error information including stderr, stdout, etc.'),
        ),
    ]
