# Generated by Django 5.1.6 on 2025-10-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_analysis', '0016_analysistask_error_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Priority level (higher number = higher priority)'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='queue_position',
            field=models.PositiveIntegerField(blank=True, help_text='Position in the analysis queue', null=True),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='queued_at',
            field=models.DateTimeField(blank=True, help_text='When the task was added to the queue', null=True),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='analysistask',
            index=models.Index(fields=['status', 'queue_position'], name='package_ana_status_0f87a3_idx'),
        ),
        migrations.AddIndex(
            model_name='analysistask',
            index=models.Index(fields=['priority', 'queued_at'], name='package_ana_priorit_d7d99d_idx'),
        ),
    ]
