# Generated by Django 5.1.6 on 2025-10-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_analysis', '0017_analysistask_priority_analysistask_queue_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='container_id',
            field=models.CharField(blank=True, help_text='Docker container ID if running', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, help_text='Last heartbeat from running container', null=True),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='timeout_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Timeout in minutes for this task'),
        ),
        migrations.AddIndex(
            model_name='analysistask',
            index=models.Index(fields=['status', 'started_at'], name='package_ana_status_9ff0e2_idx'),
        ),
        migrations.AddIndex(
            model_name='analysistask',
            index=models.Index(fields=['container_id'], name='package_ana_contain_07c0ee_idx'),
        ),
    ]
