# Generated by Django 5.1.6 on 2025-10-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_analysis', '0018_analysistask_container_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysistask',
            name='timeout_minutes',
            field=models.PositiveIntegerField(default=120, help_text='Timeout in minutes for this task'),
        ),
    ]
