# Generated by Django 5.1.6 on 2025-10-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_analysis', '0019_alter_analysistask_timeout_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysistask',
            name='timeout_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Timeout in minutes for this task'),
        ),
    ]
